### ISSUE TITLE
Histogram empty with `tokio-console 0.1.1`

### ISSUE THREAD

**Issue by benthillerkus** [tokio-rs/console#262] opened 2022-01-19 00:14 UTC
![image](https://user-images.githubusercontent.com/29630575/150054869-677c031f-ca0d-4249-a8d5-4b24a69dc8d9.png)

Also note that the ID seems to be different, while the rest of the stats is the same.
# Last working release

`tokio-console 0.1.0`

# Steps to reproduce

1. `cargo install tokio-console`
2. `tokio-console -V` -> `tokio-console 0.1.1`
3. `git clone https://github.com/tokio-rs/console`
4. `cd console\console-subscriber\examples`
5. `cargo run --example app`
6. `tokio-console`
![image](https://user-images.githubusercontent.com/29630575/150038939-3cea5108-3629-4a0e-8f6e-bed56e3fecf4.png)

# System Info
`rustc -V` -> `rustc 1.58.0 (02072b482 2022-01-11)`
Windows 10 21H2 build `19044.1466`

**Comment by benthillerkus** [comment] 2022-01-19 02:36
The problem was introduced in 095b1ef019942ab95ce1d424b3a3207b45098b3d

**Comment by hawkw** [comment] 2022-01-19 03:54
Thanks for the report!

I believe this is related to the issue fixed in #251, but it looks like --- for whatever reason --- that commit didn't fix this. I'll have to take a closer look.

**Comment by niklaslong** [comment] 2022-01-20 10:25
I don't think this is platform specific, I've managed to reproduce on M1 and Linux (Ubuntu).

**Comment by hawkw** [comment] 2022-01-20 18:14
I agree that it's almost certainly not platform specific.

**Comment by jtgeibel** [comment] 2022-01-28 01:25
I've opened #269 which should fix this.

**Closed as completed** 2022-01-28 19:18 UTC
